In [1]:
import numpy as np
lst=[1,2,3,4,5]
arr=np.array(lst)
print(arr)

[1 2 3 4 5]


In [2]:
print(np.arange(0,20,5))

[ 0  5 10 15]


In [3]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [5]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [13]:
np.eye(N=4,M=4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(0,1,5,dtype=np.float32)

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [ ]:
arr,step=(0,2,5,retstep==True)
print(arr)
print(step)

NameError: name 'retstep' is not defined

In [20]:
print(np.log(np.exp(5.2)))

5.2


In [22]:
mat=np.array(([1,2,3],[4,5,6]))
print(mat)

[[1 2 3]
 [4 5 6]]


In [23]:
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
print(vec4.reshape(10,1))

NameError: name 'vec4' is not defined

In [27]:
vec4=np.array([1,2,3,4])
vec5=np.array([5,6,7,8])
print(vec4)
print(vec5)

[1 2 3 4]
[5 6 7 8]


In [29]:
print(vec4+vec5)

[ 6  8 10 12]


In [31]:
a=np.array(([1,2],[2,3]))
b=np.array(([3,2],[5,3]))
print(a)
print(b)

[[1 2]
 [2 3]]
[[3 2]
 [5 3]]


In [34]:
print(np.matmul(a,b))

[[13  8]
 [21 13]]


In [36]:
vec7=np.array(['red','blue','pink','green'])
print(vec7)

['red' 'blue' 'pink' 'green']


In [37]:
np.unique(vec7)

array(['blue', 'green', 'pink', 'red'], dtype='<U5')

In [39]:
print(vec7=='blue')
print(vec7!='blue')

[False  True False False]
[ True False  True  True]


In [40]:
uniform_random=np.random.rand(3,3)
print(uniform_random)

[[0.97897297 0.17081131 0.93263765]
 [0.51724334 0.17757055 0.29148826]
 [0.09773587 0.25462762 0.13622612]]


In [41]:
normal_random=np.random.randn(3,3)
print(normal_random)

[[ 0.38288169 -0.09832092 -0.38855419]
 [ 0.01270554 -1.69750081  0.66920968]
 [ 0.69216922  0.41317788  0.18842961]]


In [56]:
np.transpose(normal_random)

array([[ 0.38288169,  0.01270554,  0.69216922],
       [-0.09832092, -1.69750081,  0.41317788],
       [-0.38855419,  0.66920968,  0.18842961]])

In [45]:
print(normal_random[0])
print(normal_random[0][0])
print(normal_random[0,0])
print(normal_random[0:2,1:3])

[ 0.38288169 -0.09832092 -0.38855419]
0.3828816865146599
0.3828816865146599
[[-0.09832092 -0.38855419]
 [-1.69750081  0.66920968]]


In [48]:
rand_vec=np.random.randn(10)
print(rand_vec)

[ 0.74783797 -0.98093452  0.38761903 -0.78508635  1.34549663  1.35923807
  0.10047647  0.02308574  0.48834848  0.54894859]


In [49]:
rand_mat=np.random.rand(3,5)
print(rand_mat)

[[0.37881849 0.80602065 0.98603581 0.26117534 0.12386596]
 [0.31939925 0.20666959 0.93178395 0.42081267 0.94153005]
 [0.85209763 0.48429513 0.58886876 0.52658526 0.40965235]]


In [51]:
sub_mat=rand_mat[0:2,0:2]
print(sub_mat)

[[0.37881849 0.80602065]
 [0.31939925 0.20666959]]


In [52]:
sub_mat[:]=4
print(sub_mat)

[[4. 4.]
 [4. 4.]]


In [53]:
print(rand_mat)

[[4.         4.         0.98603581 0.26117534 0.12386596]
 [4.         4.         0.93178395 0.42081267 0.94153005]
 [0.85209763 0.48429513 0.58886876 0.52658526 0.40965235]]


In [55]:
ranarr=np.random.randint(1,50,5)
print(ranarr)
ranarr=np.random.randint(1,50)
print(ranarr)

[20 11 17 49 20]
11


PANDAS

In [57]:
import pandas as pd

In [62]:
lebels=['a','b','c']
my_list=[10,20,30]

print(my_list)
pd.Series(data=my_list)
pd.Series(my_list,lebels)

[10, 20, 30]


a    10
b    20
c    30
dtype: int64

In [63]:
arr=np.array([40,50,60])
pd.Series(arr)

0    40
1    50
2    60
dtype: int64

In [73]:
df=pd.DataFrame([[1,2,3,4],[5,6,7,8]],index=['a','b'],columns=['x','y','z','w'])
df

,x,y,z,w
a,1,2,3,4
b,5,6,7,8


In [77]:
from numpy.random import randn
df=pd.DataFrame(randn(4,4),index='A B C D'.split(),columns='w x y z'.split())
df

,w,x,y,z
A,0.285952,1.239835,0.685400,0.606910
B,0.970468,-0.730594,-1.410898,0.499306
C,0.034004,-0.089934,1.784464,0.147127
D,0.665709,-0.050779,0.204478,-1.564477


In [79]:
df[['w','y']]

,w,y
A,0.285952,0.685400
B,0.970468,-1.410898
C,0.034004,1.784464
D,0.665709,0.204478


In [83]:
df1=df.drop('D')
df1

,w,x,y,z
A,0.285952,1.239835,0.685400,0.606910
B,0.970468,-0.730594,-1.410898,0.499306
C,0.034004,-0.089934,1.784464,0.147127


In [82]:
df

,w,x,y,z
A,0.285952,1.239835,0.685400,0.606910
B,0.970468,-0.730594,-1.410898,0.499306
C,0.034004,-0.089934,1.784464,0.147127
D,0.665709,-0.050779,0.204478,-1.564477


In [84]:
df.loc[['A','B'],['x','y']]

,x,y
A,1.239835,0.685400
B,-0.730594,-1.410898


In [85]:
df>0

,w,x,y,z
A,True,True,True,True
B,True,False,False,True
C,True,False,True,True
D,True,False,True,False


In [86]:
df[df>0]

,w,x,y,z
A,0.285952,1.239835,0.685400,0.606910
B,0.970468,NaN,NaN,0.499306
C,0.034004,NaN,1.784464,0.147127
D,0.665709,NaN,0.204478,NaN


In [87]:
df['x']>0

A     True
B    False
C    False
D    False
Name: x, dtype: bool

In [88]:
df[df['x']>0]

,w,x,y,z
A,0.285952,1.239835,0.6854,0.60691


In [93]:
np.random.seed(8)
df2=pd.DataFrame(randn(4,4),index='A B C D'.split(),columns='w x y z'.split())
df2

,w,x,y,z
A,0.091205,1.091283,-1.946970,-1.386350
B,-2.296492,2.409834,1.727836,2.204556
C,0.794828,0.976421,-1.183427,1.916364
D,-1.123327,-0.664035,-0.378359,-0.791615


In [97]:
newind=['gh','ui','rt','fg']
df['states']=newind
df

,w,x,y,z,states
A,0.285952,1.239835,0.685400,0.606910,gh
B,0.970468,-0.730594,-1.410898,0.499306,ui
C,0.034004,-0.089934,1.784464,0.147127,rt
D,0.665709,-0.050779,0.204478,-1.564477,fg


multiindex and groupby

In [98]:
a=("sachin","ganguly","dravid")
b=("mumbai","kolkata","jkl")
list(zip(a,b))


[('sachin', 'mumbai'), ('ganguly', 'kolkata'), ('dravid', 'jkl')]